### ISSUE TITLE
Find place for dired commands in keybindings

### ISSUE THREAD

**Issue by punassuming** [punassuming/ranger.el#10]
- flatten
- rename

**Comment by jtbm37** [comment]
is this to improve compatibility with dired commands ?

For example when I attempt to rename a file `dired-do-rename` the current path is not passed to it.

Example:
- execute `ranger`
- go to ~/Downloads/Dired1/FileToRename.sh
- press `R` (`dired-do-rename`)
- helm or ido starts at `~/` instead of `~/Downloads/Dired1/`

**Comment by vyp** [comment]
@jtbm37 +1 to that.

**Comment by punassuming** [comment]
@jtbm37 and @vyp, I will look into this,  dired might depend on parsing the buffer to find the subdir parent on these commands.  The hack I have put in to delete the dired header line might break it. Any other common commands that are wrong?

**Comment by vyp** [comment]
@ralesi Thanks!

> Any other common commands that are wrong?

I haven't actually been using it that much lately because I'm still quite new to emacs and figuring out other things (so I've been using plain old coreutils to do file management instead of dired) still, so no I haven't come across other "unintegrated" commands, but that probably doesn't mean there aren't any.

**Comment by punassuming** [comment]
@jtbm37, let me know if you still have this issue with the latest commits.
