### ISSUE TITLE
Show dotfiles toggle doesn't work correctly if you don't show them by default

### ISSUE THREAD

**Issue by synic** [punassuming/ranger.el#48]
If you have `ranger-show-dotfiles` set to `nil`, and you open a directory and press `zh`, only the left panel will update.  The center panel will continue not showing dotfiles.

**Comment by punassuming** [comment]
@synic.  I can't reproduce this.  When I start `ranger` after setting ranger-show-dotfiles to nil, `zh` does let me see the `.git` directory in the center panel.  Moving down one directory, so that the previous directory is now listed as a parent, `zh` again toggles the visibility of the `.git` folder.

**Comment by synic** [comment]
Hrmm, you are right.  I don't know if I actually saw anything at this point, I cannot reproduce it.
