### ISSUE TITLE
Disable ranger keymap in Wdired mode

### ISSUE THREAD

**Issue by Alexander-Miller** [punassuming/ranger.el#84]
In vanilla emacs activating Wdired-mode (`C-x C-q`) would do away with all the usual dired keybindings - allowing you to edit the contents of the dired buffer with the full power of your usual text editing tools.

This seems currently not possible with ranger because it keeps its keymap in Wdired mode making any text editing impossible. Ranger should therefore hide its keymap to allow for compatibility with Wdired mode.

**Comment by punassuming** [comment]
@Alexander-Miller, the quick fix, would be to drop back into dired with `C-p` and then use `wdired`,  I will look into why ranger overrides the map, even in emacs mode.

**Comment by punassuming** [comment]
@Alexander-Miller, I rewrote the mode creation based on this problem and it should help with wdired usage in ranger.  I have had success using C-c C-e to edit the filenames.  Let me know if you have any issues.

**Comment by Alexander-Miller** [comment]
I have some good news and some bad news (mostly bad for me).

Good news is that everything works with `emacs -q`, so you did everything right.

Bad news is ranger completely breaks in various ways with my own configuration. Likely culprits are dired-hacks, dired+ and shackle. Probably the latter, since it wouldn't be the first buffer management package that interferes with ranger - I was going to open another issue about golden-ratio-mode breaking ranger's column buffer setup.

An example of the issues: Loading nothing but my package list and [misc settings](https://github.com/Alexander-Miller/dotfiles/blob/master/.emacs.d/init/misc-settings-cfg.el)(my bet is on line 98) ranger ends up doing [this](http://i.imgur.com/K4NCWpO.png).

I'll report back with more details once I've done some thorough debugging.

edit: dired-hacks, not diredx

**Comment by punassuming** [comment]
I will look into shackle,  havent tried that package yet.   The other two should provide no issues (ranger actually requires dired-x). 

Rich

On Mon, Jan 18, 2016 at 1:01 PM -0800, "Alexander-Miller" notifications@github.com wrote:

I have some good news and some bad news (mostly bad for me).

Good news is that everything works with emacs -q, so you did everything right.

Bad news is ranger completely breaks in various ways with my own configuration. Likely culprits are diredx, dired+ and shackle. Probably the latter, since it wouldn't be the first buffer management package that interferes with ranger - I was going to open another issue about golden-ratio-mode breaking ranger's column buffer setup.

An example of the issues: Loading nothing but my package list and misc settings(my bet is on line 98) ranger ends up doing this.

I'll report back with more details once I've done some thorough debugging.

**Comment by Alexander-Miller** [comment]
I'm done debugging. It's all shackle's fault. The moment it gets a default rule, at least of the `:select t`/`:noselect t` variety, ranger's window configuration goes gaga. I've tried adding
`(".*ranger.*"      :regexp t :ignore   t)`
`(".*preview.*"     :regexp t :ignore   t)`
`('ranger-mode      :ignore   t)`
`('dired-mode       :ignore   t)`
to my shackle-rules and that only left me with one column like I'm in deer-mode (which is unaffected by this whole issue).
Locally turning off shackle-mode didn't work either, it is global, so removing it for just ranger buffers won't work.

Unless you can come up with something I guess the solution is just to tell people not to use shackle's default rule feature. I, for one, don't mind, only reason I had that default rule was because why not.

**Comment by punassuming** [comment]
@Alexander-Miller, check with the latest changes.  I just tried turning on `shackle-mode`, and I didn't have any issues with ranger.
